name: DBetterModel
author: meigoc
authors: ['gleb_petrovich (meigoc)', 'isnsest']
version: ${version}
main: net.openproject.dbettermodel.DBetterModel
depend: [Denizen, BetterModel]
website: https://github.com/meigoc/DBetterModel

api-version: '1.21'

softdepend: []
